package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "ACT_ACCOUNT".
 */
public class ActAccountDao extends AbstractDao<ActAccount, Long> {

    public static final String TABLENAME = "ACT_ACCOUNT";
    private DaoSession daoSession;
    private Query<ActAccount> client_AccountsQuery;
    private String selectDeep;

    public ActAccountDao(DaoConfig config) {
        super(config);
    }

	public ActAccountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"ACT_ACCOUNT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DIRECTUM_ID\" INTEGER," + // 1: directumID
                "\"NAME\" TEXT," + // 2: name
                "\"ADDRESS\" TEXT," + // 3: address
                "\"STATUS\" INTEGER," + // 4: status
                "\"CLIENT_ID\" INTEGER NOT NULL );"); // 5: clientID
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACT_ACCOUNT\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, ActAccount entity) {
		stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer directumID = entity.getDirectumID();
        if (directumID != null) {
            stmt.bindLong(2, directumID);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(4, address);
        }

		Integer status = entity.getStatus();
		if (status != null) {
			stmt.bindLong(5, status);
		}
		stmt.bindLong(6, entity.getClientID());
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, ActAccount entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Integer directumID = entity.getDirectumID();
		if (directumID != null) {
			stmt.bindLong(2, directumID);
		}

		String name = entity.getName();
		if (name != null) {
			stmt.bindString(3, name);
		}

		String address = entity.getAddress();
		if (address != null) {
			stmt.bindString(4, address);
		}
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(5, status);
        }
        stmt.bindLong(6, entity.getClientID());
	}

	@Override
	protected final void attachEntity(ActAccount entity) {
		super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ActAccount readEntity(Cursor cursor, int offset) {
        ActAccount entity = new ActAccount( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // directumID
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
		        cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // address
		        cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // status
		        cursor.getLong(offset + 5) // clientID
        );
	    return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ActAccount entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDirectumID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAddress(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStatus(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setClientID(cursor.getLong(offset + 5));
    }

	@Override
	protected final Long updateKeyAfterInsert(ActAccount entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(ActAccount entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(ActAccount entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
	}

	/** Internal query to resolve the "accounts" to-many relationship of Client. */
	public List<ActAccount> _queryClient_Accounts(long clientID) {
        synchronized (this) {
            if (client_AccountsQuery == null) {
                QueryBuilder<ActAccount> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ClientID.eq(null));
                client_AccountsQuery = queryBuilder.build();
            }
        }
        Query<ActAccount> query = client_AccountsQuery.forCurrentThread();
        query.setParameter(0, clientID);
        return query.list();
    }

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getClientDao().getAllColumns());
            builder.append(" FROM ACT_ACCOUNT T");
            builder.append(" LEFT JOIN CLIENT T0 ON T.\"CLIENT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected ActAccount loadCurrentDeep(Cursor cursor, boolean lock) {
        ActAccount entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Client client = loadCurrentOther(daoSession.getClientDao(), cursor, offset);
	    if(client != null) {
		    entity.setClient(client);
        }

	    return entity;
    }
    
    public ActAccount loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

	    String[] keyArray = new String[] { key.toString() };
	    Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

	/** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
	public List<ActAccount> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ActAccount> list = new ArrayList<ActAccount>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
	    return list;
    }
    
    protected List<ActAccount> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }

	/** A raw-style query where you can pass any WHERE clause and arguments. */
	public List<ActAccount> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
    
    /**
     * Properties of entity ActAccount.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DirectumID = new Property(1, Integer.class, "directumID", false, "DIRECTUM_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Address = new Property(3, String.class, "address", false, "ADDRESS");
        public final static Property Status = new Property(4, Integer.class, "status", false, "STATUS");
        public final static Property ClientID = new Property(5, long.class, "clientID", false, "CLIENT_ID");
    }
 
}
