package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.internal.SqlUtils;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "ACT_CONTACT".
 */
public class ActContactDao extends AbstractDao<ActContact, Long> {

    public static final String TABLENAME = "ACT_CONTACT";
    private DaoSession daoSession;
    private String selectDeep;


    public ActContactDao(DaoConfig config) {
        super(config);
    }

	public ActContactDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"ACT_CONTACT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ACT_CONTACT_ID\" INTEGER," + // 1: actContactID
                "\"NAME\" TEXT," + // 2: name
                "\"CLIENT_ID\" INTEGER," + // 3: clientID
                "\"ACCOUNT_ID\" INTEGER);"); // 4: accountID
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACT_CONTACT\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, ActContact entity) {
		stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer actContactID = entity.getActContactID();
        if (actContactID != null) {
            stmt.bindLong(2, actContactID);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Long clientID = entity.getClientID();
        if (clientID != null) {
            stmt.bindLong(4, clientID);
        }

		Long accountID = entity.getAccountID();
		if (accountID != null) {
			stmt.bindLong(5, accountID);
		}
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, ActContact entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Integer actContactID = entity.getActContactID();
		if (actContactID != null) {
			stmt.bindLong(2, actContactID);
		}

		String name = entity.getName();
		if (name != null) {
			stmt.bindString(3, name);
		}

		Long clientID = entity.getClientID();
		if (clientID != null) {
			stmt.bindLong(4, clientID);
		}
 
        Long accountID = entity.getAccountID();
        if (accountID != null) {
            stmt.bindLong(5, accountID);
        }
	}

	@Override
	protected final void attachEntity(ActContact entity) {
		super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ActContact readEntity(Cursor cursor, int offset) {
        ActContact entity = new ActContact( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // actContactID
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
		        cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // clientID
		        cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // accountID
        );
	    return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ActContact entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setActContactID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setClientID(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setAccountID(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
    }

	@Override
	protected final Long updateKeyAfterInsert(ActContact entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(ActContact entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(ActContact entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
	}
    
    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getClientDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getActAccountDao().getAllColumns());
            builder.append(" FROM ACT_CONTACT T");
            builder.append(" LEFT JOIN CLIENT T0 ON T.\"CLIENT_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN ACT_ACCOUNT T1 ON T.\"ACCOUNT_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected ActContact loadCurrentDeep(Cursor cursor, boolean lock) {
        ActContact entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Client client = loadCurrentOther(daoSession.getClientDao(), cursor, offset);
        entity.setClient(client);
        offset += daoSession.getClientDao().getAllColumns().length;

        ActAccount actAccount = loadCurrentOther(daoSession.getActAccountDao(), cursor, offset);
        entity.setActAccount(actAccount);

	    return entity;
    }
    
    public ActContact loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

	    String[] keyArray = new String[] { key.toString() };
	    Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

	/** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
	public List<ActContact> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ActContact> list = new ArrayList<ActContact>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
	    return list;
    }
    
    protected List<ActContact> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }

	/** A raw-style query where you can pass any WHERE clause and arguments. */
	public List<ActContact> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
    
    /**
     * Properties of entity ActContact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ActContactID = new Property(1, Integer.class, "actContactID", false, "ACT_CONTACT_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property ClientID = new Property(3, Long.class, "clientID", false, "CLIENT_ID");
        public final static Property AccountID = new Property(4, Long.class, "accountID", false, "ACCOUNT_ID");
    }
 
}
