package database;

import org.greenrobot.greendao.DaoException;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.ToOne;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ACT_CONTACT".
 */
@Entity(active = true)
public class ActContact {

	@Id
	private Long id;
    private Integer actContactID;
    private String name;
    private Long clientID;
    private Long accountID;

	/**
	 * Used to resolve relations
	 */
	@Generated
	private transient DaoSession daoSession;

	/**
	 * Used for active entity operations.
	 */
	@Generated
	private transient ActContactDao myDao;

	@ToOne(joinProperty = "clientID")
	private Client client;

	@Generated
	private transient Long client__resolvedKey;

	@ToOne(joinProperty = "accountID")
	private ActAccount actAccount;

	@Generated
	private transient Long actAccount__resolvedKey;

    @Generated
    public ActContact() {
    }

    public ActContact(Long id) {
	    this.id = id;
    }

    @Generated
    public ActContact(Long id, Integer actContactID, String name, Long clientID, Long accountID) {
        this.id = id;
        this.actContactID = actContactID;
        this.name = name;
        this.clientID = clientID;
        this.accountID = accountID;
    }

	/** called by internal mechanisms, do not call yourself. */
	@Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getActContactDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getActContactID() {
        return actContactID;
    }

    public void setActContactID(Integer actContactID) {
        this.actContactID = actContactID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getClientID() {
        return clientID;
    }

    public void setClientID(Long clientID) {
        this.clientID = clientID;
    }

    public Long getAccountID() {
        return accountID;
    }

    public void setAccountID(Long accountID) {
        this.accountID = accountID;
    }

	/** To-one relationship, resolved on first access. */
	@Generated
    public Client getClient() {
        Long __key = this.clientID;
        if (client__resolvedKey == null || !client__resolvedKey.equals(__key)) {
	        __throwIfDetached();
	        ClientDao targetDao = daoSession.getClientDao();
            Client clientNew = targetDao.load(__key);
            synchronized (this) {
	            client = clientNew;
	            client__resolvedKey = __key;
            }
        }
	    return client;
    }

    @Generated
    public void setClient(Client client) {
        synchronized (this) {
            this.client = client;
            clientID = client == null ? null : client.getId();
            client__resolvedKey = clientID;
        }
    }

	/** To-one relationship, resolved on first access. */
	@Generated
    public ActAccount getActAccount() {
        Long __key = this.accountID;
        if (actAccount__resolvedKey == null || !actAccount__resolvedKey.equals(__key)) {
	        __throwIfDetached();
	        ActAccountDao targetDao = daoSession.getActAccountDao();
            ActAccount actAccountNew = targetDao.load(__key);
            synchronized (this) {
                actAccount = actAccountNew;
	            actAccount__resolvedKey = __key;
            }
        }
        return actAccount;
    }

    @Generated
    public void setActAccount(ActAccount actAccount) {
        synchronized (this) {
            this.actAccount = actAccount;
            accountID = actAccount == null ? null : actAccount.getId();
            actAccount__resolvedKey = accountID;
        }
    }

	/**
	 * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
	 * Entity must attached to an entity context.
	 */
    @Generated
    public void delete() {
	    __throwIfDetached();
	    myDao.delete(this);
    }

	/**
	 * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
	 * Entity must attached to an entity context.
	 */
    @Generated
    public void update() {
	    __throwIfDetached();
	    myDao.update(this);
    }

	/**
	 * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
	 * Entity must attached to an entity context.
	 */
    @Generated
    public void refresh() {
	    __throwIfDetached();
	    myDao.refresh(this);
    }

	@Generated
	private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
