package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ACT_REASON".
 */
@Entity
public class ActReason {

	@Id
	private Long id;
    private Integer actReasonID;
    private String name;

	@Generated
	public ActReason() {
    }

    public ActReason(Long id) {
        this.id = id;
    }

	@Generated
	public ActReason(Long id, Integer actReasonID, String name) {
        this.id = id;
        this.actReasonID = actReasonID;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getActReasonID() {
        return actReasonID;
    }

    public void setActReasonID(Integer actReasonID) {
        this.actReasonID = actReasonID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
