package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ACT_TYPE".
 */
@Entity
public class ActType {

	@Id
	private Long id;
    private Integer actTypeID;
    private String name;

	@Generated
	public ActType() {
    }

    public ActType(Long id) {
        this.id = id;
    }

	@Generated
	public ActType(Long id, Integer actTypeID, String name) {
        this.id = id;
        this.actTypeID = actTypeID;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getActTypeID() {
        return actTypeID;
    }

    public void setActTypeID(Integer actTypeID) {
        this.actTypeID = actTypeID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
