package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "APPOINTMENT_ATTENDER".
 */
@Entity
public class AppointmentAttender {

	@Id
	private Long id;
    private Long AppointmentId;
    private String Email;

	@Generated
	public AppointmentAttender() {
    }

    public AppointmentAttender(Long id) {
        this.id = id;
    }

	@Generated
	public AppointmentAttender(Long id, Long AppointmentId, String Email) {
        this.id = id;
        this.AppointmentId = AppointmentId;
        this.Email = Email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAppointmentId() {
        return AppointmentId;
    }

    public void setAppointmentId(Long AppointmentId) {
        this.AppointmentId = AppointmentId;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

}
