package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CLEANING_REASON".
 */
@Entity
public class CleaningReason {

	@Id
	private Long id;
    private Integer ReasonID;
    private String ReasonName;

	@Generated
	public CleaningReason() {
    }

    public CleaningReason(Long id) {
        this.id = id;
    }

	@Generated
	public CleaningReason(Long id, Integer ReasonID, String ReasonName) {
        this.id = id;
        this.ReasonID = ReasonID;
        this.ReasonName = ReasonName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getReasonID() {
        return ReasonID;
    }

    public void setReasonID(Integer ReasonID) {
        this.ReasonID = ReasonID;
    }

    public String getReasonName() {
        return ReasonName;
    }

    public void setReasonName(String ReasonName) {
        this.ReasonName = ReasonName;
    }

}
