package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "CLEANING_REASON".
 */
public class CleaningReasonDao extends AbstractDao<CleaningReason, Long> {

    public static final String TABLENAME = "CLEANING_REASON";

    public CleaningReasonDao(DaoConfig config) {
        super(config);
    }


    public CleaningReasonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"CLEANING_REASON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REASON_ID\" INTEGER," + // 1: ReasonID
                "\"REASON_NAME\" TEXT);"); // 2: ReasonName
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLEANING_REASON\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, CleaningReason entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer ReasonID = entity.getReasonID();
        if (ReasonID != null) {
            stmt.bindLong(2, ReasonID);
        }

        String ReasonName = entity.getReasonName();
        if (ReasonName != null) {
            stmt.bindString(3, ReasonName);
        }
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, CleaningReason entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Integer ReasonID = entity.getReasonID();
		if (ReasonID != null) {
			stmt.bindLong(2, ReasonID);
		}

		String ReasonName = entity.getReasonName();
		if (ReasonName != null) {
			stmt.bindString(3, ReasonName);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public CleaningReason readEntity(Cursor cursor, int offset) {
        CleaningReason entity = new CleaningReason( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // ReasonID
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // ReasonName
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, CleaningReason entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReasonID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setReasonName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

	@Override
	protected final Long updateKeyAfterInsert(CleaningReason entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(CleaningReason entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(CleaningReason entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity CleaningReason.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ReasonID = new Property(1, Integer.class, "ReasonID", false, "REASON_ID");
        public final static Property ReasonName = new Property(2, String.class, "ReasonName", false, "REASON_NAME");
    }
    
}
