package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "CONTACT_CLIENT".
 */
public class ContactClientDao extends AbstractDao<ContactClient, Long> {

    public static final String TABLENAME = "CONTACT_CLIENT";

    public ContactClientDao(DaoConfig config) {
        super(config);
    }


    public ContactClientDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"CONTACT_CLIENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CLIENT_ID\" INTEGER," + // 1: clientID
                "\"CONTACT_ID\" INTEGER);"); // 2: contactID
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTACT_CLIENT\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, ContactClient entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer clientID = entity.getClientID();
        if (clientID != null) {
            stmt.bindLong(2, clientID);
        }

        Integer contactID = entity.getContactID();
        if (contactID != null) {
            stmt.bindLong(3, contactID);
        }
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, ContactClient entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Integer clientID = entity.getClientID();
		if (clientID != null) {
			stmt.bindLong(2, clientID);
		}

		Integer contactID = entity.getContactID();
		if (contactID != null) {
			stmt.bindLong(3, contactID);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public ContactClient readEntity(Cursor cursor, int offset) {
        ContactClient entity = new ContactClient( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // clientID
		        cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // contactID
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, ContactClient entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClientID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setContactID(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
    }

	@Override
	protected final Long updateKeyAfterInsert(ContactClient entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(ContactClient entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(ContactClient entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity ContactClient.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClientID = new Property(1, Integer.class, "clientID", false, "CLIENT_ID");
        public final static Property ContactID = new Property(2, Integer.class, "contactID", false, "CONTACT_ID");
    }
    
}
