package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "COUNTRY".
 */
@Entity
public class Country {

	@Id
	private Long id;
    private String CountryUID;
    private String CountryName;
    private Integer NeedPatentOrPermission;

	@Generated
	public Country() {
    }

    public Country(Long id) {
        this.id = id;
    }

	@Generated
	public Country(Long id, String CountryUID, String CountryName, Integer NeedPatentOrPermission) {
        this.id = id;
        this.CountryUID = CountryUID;
        this.CountryName = CountryName;
        this.NeedPatentOrPermission = NeedPatentOrPermission;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCountryUID() {
        return CountryUID;
    }

    public void setCountryUID(String CountryUID) {
        this.CountryUID = CountryUID;
    }

    public String getCountryName() {
        return CountryName;
    }

    public void setCountryName(String CountryName) {
        this.CountryName = CountryName;
    }

    public Integer getNeedPatentOrPermission() {
        return NeedPatentOrPermission;
    }

    public void setNeedPatentOrPermission(Integer NeedPatentOrPermission) {
        this.NeedPatentOrPermission = NeedPatentOrPermission;
    }

}
