package database;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig actTypeDaoConfig;
    private final DaoConfig actReasonDaoConfig;
    private final DaoConfig contactClientDaoConfig;
    private final DaoConfig contactAccountDaoConfig;
    private final DaoConfig clientDaoConfig;
    private final DaoConfig actAccountDaoConfig;
    private final DaoConfig actServiceTypeDaoConfig;
    private final DaoConfig actContactDaoConfig;
    private final DaoConfig nomenclatureGroupDaoConfig;
    private final DaoConfig mobileDaoConfig;
    private final DaoConfig partTimeDaoConfig;
    private final DaoConfig scheduleDaoConfig;
    private final DaoConfig vidTaskDaoConfig;
    private final DaoConfig taskEmployeeDaoConfig;
    private final DaoConfig countryDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig personPhotoDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig tSTaskDaoConfig;
    private final DaoConfig checkInLogDaoConfig;
    private final DaoConfig requestDaoConfig;
    private final DaoConfig requestPhotoDaoConfig;
    private final DaoConfig serviceRequestServantDaoConfig;
    private final DaoConfig serviceRequestLogDaoConfig;
    private final DaoConfig serviceRequestFileDaoConfig;
    private final DaoConfig serviceRequestPhotoDaoConfig;
    private final DaoConfig serviceRequestDaoConfig;
    private final DaoConfig appointmentAttenderDaoConfig;
    private final DaoConfig appointmentDaoConfig;
    private final DaoConfig potSellDaoConfig;
    private final DaoConfig workTypeDaoConfig;
    private final DaoConfig cleaningReasonDaoConfig;
    private final DaoConfig facilityUrgencyTypeDaoConfig;
    private final DaoConfig fakeDaoConfig;
    private final DaoConfig orioTypeDaoConfig;
    private final DaoConfig orioArticleDaoConfig;

    private final ActTypeDao actTypeDao;
    private final ActReasonDao actReasonDao;
    private final ContactClientDao contactClientDao;
    private final ContactAccountDao contactAccountDao;
    private final ClientDao clientDao;
    private final ActAccountDao actAccountDao;
    private final ActServiceTypeDao actServiceTypeDao;
    private final ActContactDao actContactDao;
    private final NomenclatureGroupDao nomenclatureGroupDao;
    private final MobileDao mobileDao;
    private final PartTimeDao partTimeDao;
    private final ScheduleDao scheduleDao;
    private final VidTaskDao vidTaskDao;
    private final TaskEmployeeDao taskEmployeeDao;
    private final CountryDao countryDao;
    private final PersonDao personDao;
    private final PersonPhotoDao personPhotoDao;
    private final TaskDao taskDao;
    private final TSTaskDao tSTaskDao;
    private final CheckInLogDao checkInLogDao;
    private final RequestDao requestDao;
    private final RequestPhotoDao requestPhotoDao;
    private final ServiceRequestServantDao serviceRequestServantDao;
    private final ServiceRequestLogDao serviceRequestLogDao;
    private final ServiceRequestFileDao serviceRequestFileDao;
    private final ServiceRequestPhotoDao serviceRequestPhotoDao;
    private final ServiceRequestDao serviceRequestDao;
    private final AppointmentAttenderDao appointmentAttenderDao;
    private final AppointmentDao appointmentDao;
    private final PotSellDao potSellDao;
    private final WorkTypeDao workTypeDao;
    private final CleaningReasonDao cleaningReasonDao;
    private final FacilityUrgencyTypeDao facilityUrgencyTypeDao;
    private final FakeDao fakeDao;
    private final OrioTypeDao orioTypeDao;
    private final OrioArticleDao orioArticleDao;

	public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
			daoConfigMap) {
        super(db);

        actTypeDaoConfig = daoConfigMap.get(ActTypeDao.class).clone();
        actTypeDaoConfig.initIdentityScope(type);

        actReasonDaoConfig = daoConfigMap.get(ActReasonDao.class).clone();
        actReasonDaoConfig.initIdentityScope(type);

        contactClientDaoConfig = daoConfigMap.get(ContactClientDao.class).clone();
        contactClientDaoConfig.initIdentityScope(type);

        contactAccountDaoConfig = daoConfigMap.get(ContactAccountDao.class).clone();
        contactAccountDaoConfig.initIdentityScope(type);

        clientDaoConfig = daoConfigMap.get(ClientDao.class).clone();
        clientDaoConfig.initIdentityScope(type);

        actAccountDaoConfig = daoConfigMap.get(ActAccountDao.class).clone();
        actAccountDaoConfig.initIdentityScope(type);

        actServiceTypeDaoConfig = daoConfigMap.get(ActServiceTypeDao.class).clone();
        actServiceTypeDaoConfig.initIdentityScope(type);

        actContactDaoConfig = daoConfigMap.get(ActContactDao.class).clone();
        actContactDaoConfig.initIdentityScope(type);

        nomenclatureGroupDaoConfig = daoConfigMap.get(NomenclatureGroupDao.class).clone();
        nomenclatureGroupDaoConfig.initIdentityScope(type);

        mobileDaoConfig = daoConfigMap.get(MobileDao.class).clone();
        mobileDaoConfig.initIdentityScope(type);

        partTimeDaoConfig = daoConfigMap.get(PartTimeDao.class).clone();
        partTimeDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        vidTaskDaoConfig = daoConfigMap.get(VidTaskDao.class).clone();
        vidTaskDaoConfig.initIdentityScope(type);

        taskEmployeeDaoConfig = daoConfigMap.get(TaskEmployeeDao.class).clone();
        taskEmployeeDaoConfig.initIdentityScope(type);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        personPhotoDaoConfig = daoConfigMap.get(PersonPhotoDao.class).clone();
        personPhotoDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        tSTaskDaoConfig = daoConfigMap.get(TSTaskDao.class).clone();
        tSTaskDaoConfig.initIdentityScope(type);

        checkInLogDaoConfig = daoConfigMap.get(CheckInLogDao.class).clone();
        checkInLogDaoConfig.initIdentityScope(type);

        requestDaoConfig = daoConfigMap.get(RequestDao.class).clone();
        requestDaoConfig.initIdentityScope(type);

        requestPhotoDaoConfig = daoConfigMap.get(RequestPhotoDao.class).clone();
        requestPhotoDaoConfig.initIdentityScope(type);

        serviceRequestServantDaoConfig = daoConfigMap.get(ServiceRequestServantDao.class).clone();
        serviceRequestServantDaoConfig.initIdentityScope(type);

        serviceRequestLogDaoConfig = daoConfigMap.get(ServiceRequestLogDao.class).clone();
        serviceRequestLogDaoConfig.initIdentityScope(type);

        serviceRequestFileDaoConfig = daoConfigMap.get(ServiceRequestFileDao.class).clone();
        serviceRequestFileDaoConfig.initIdentityScope(type);

        serviceRequestPhotoDaoConfig = daoConfigMap.get(ServiceRequestPhotoDao.class).clone();
        serviceRequestPhotoDaoConfig.initIdentityScope(type);

        serviceRequestDaoConfig = daoConfigMap.get(ServiceRequestDao.class).clone();
        serviceRequestDaoConfig.initIdentityScope(type);

        appointmentAttenderDaoConfig = daoConfigMap.get(AppointmentAttenderDao.class).clone();
        appointmentAttenderDaoConfig.initIdentityScope(type);

        appointmentDaoConfig = daoConfigMap.get(AppointmentDao.class).clone();
        appointmentDaoConfig.initIdentityScope(type);

        potSellDaoConfig = daoConfigMap.get(PotSellDao.class).clone();
        potSellDaoConfig.initIdentityScope(type);

        workTypeDaoConfig = daoConfigMap.get(WorkTypeDao.class).clone();
        workTypeDaoConfig.initIdentityScope(type);

        cleaningReasonDaoConfig = daoConfigMap.get(CleaningReasonDao.class).clone();
        cleaningReasonDaoConfig.initIdentityScope(type);

        facilityUrgencyTypeDaoConfig = daoConfigMap.get(FacilityUrgencyTypeDao.class).clone();
        facilityUrgencyTypeDaoConfig.initIdentityScope(type);

        fakeDaoConfig = daoConfigMap.get(FakeDao.class).clone();
        fakeDaoConfig.initIdentityScope(type);

        orioTypeDaoConfig = daoConfigMap.get(OrioTypeDao.class).clone();
        orioTypeDaoConfig.initIdentityScope(type);

        orioArticleDaoConfig = daoConfigMap.get(OrioArticleDao.class).clone();
        orioArticleDaoConfig.initIdentityScope(type);

        actTypeDao = new ActTypeDao(actTypeDaoConfig, this);
        actReasonDao = new ActReasonDao(actReasonDaoConfig, this);
        contactClientDao = new ContactClientDao(contactClientDaoConfig, this);
        contactAccountDao = new ContactAccountDao(contactAccountDaoConfig, this);
        clientDao = new ClientDao(clientDaoConfig, this);
        actAccountDao = new ActAccountDao(actAccountDaoConfig, this);
        actServiceTypeDao = new ActServiceTypeDao(actServiceTypeDaoConfig, this);
        actContactDao = new ActContactDao(actContactDaoConfig, this);
        nomenclatureGroupDao = new NomenclatureGroupDao(nomenclatureGroupDaoConfig, this);
        mobileDao = new MobileDao(mobileDaoConfig, this);
        partTimeDao = new PartTimeDao(partTimeDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
        vidTaskDao = new VidTaskDao(vidTaskDaoConfig, this);
        taskEmployeeDao = new TaskEmployeeDao(taskEmployeeDaoConfig, this);
        countryDao = new CountryDao(countryDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        personPhotoDao = new PersonPhotoDao(personPhotoDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        tSTaskDao = new TSTaskDao(tSTaskDaoConfig, this);
        checkInLogDao = new CheckInLogDao(checkInLogDaoConfig, this);
        requestDao = new RequestDao(requestDaoConfig, this);
        requestPhotoDao = new RequestPhotoDao(requestPhotoDaoConfig, this);
        serviceRequestServantDao = new ServiceRequestServantDao(serviceRequestServantDaoConfig, this);
        serviceRequestLogDao = new ServiceRequestLogDao(serviceRequestLogDaoConfig, this);
        serviceRequestFileDao = new ServiceRequestFileDao(serviceRequestFileDaoConfig, this);
        serviceRequestPhotoDao = new ServiceRequestPhotoDao(serviceRequestPhotoDaoConfig, this);
        serviceRequestDao = new ServiceRequestDao(serviceRequestDaoConfig, this);
        appointmentAttenderDao = new AppointmentAttenderDao(appointmentAttenderDaoConfig, this);
        appointmentDao = new AppointmentDao(appointmentDaoConfig, this);
        potSellDao = new PotSellDao(potSellDaoConfig, this);
        workTypeDao = new WorkTypeDao(workTypeDaoConfig, this);
        cleaningReasonDao = new CleaningReasonDao(cleaningReasonDaoConfig, this);
        facilityUrgencyTypeDao = new FacilityUrgencyTypeDao(facilityUrgencyTypeDaoConfig, this);
        fakeDao = new FakeDao(fakeDaoConfig, this);
        orioTypeDao = new OrioTypeDao(orioTypeDaoConfig, this);
        orioArticleDao = new OrioArticleDao(orioArticleDaoConfig, this);

        registerDao(ActType.class, actTypeDao);
        registerDao(ActReason.class, actReasonDao);
        registerDao(ContactClient.class, contactClientDao);
        registerDao(ContactAccount.class, contactAccountDao);
        registerDao(Client.class, clientDao);
        registerDao(ActAccount.class, actAccountDao);
        registerDao(ActServiceType.class, actServiceTypeDao);
        registerDao(ActContact.class, actContactDao);
        registerDao(NomenclatureGroup.class, nomenclatureGroupDao);
        registerDao(Mobile.class, mobileDao);
        registerDao(PartTime.class, partTimeDao);
        registerDao(Schedule.class, scheduleDao);
        registerDao(VidTask.class, vidTaskDao);
        registerDao(TaskEmployee.class, taskEmployeeDao);
        registerDao(Country.class, countryDao);
        registerDao(Person.class, personDao);
        registerDao(PersonPhoto.class, personPhotoDao);
        registerDao(Task.class, taskDao);
        registerDao(TSTask.class, tSTaskDao);
        registerDao(CheckInLog.class, checkInLogDao);
        registerDao(Request.class, requestDao);
        registerDao(RequestPhoto.class, requestPhotoDao);
        registerDao(ServiceRequestServant.class, serviceRequestServantDao);
        registerDao(ServiceRequestLog.class, serviceRequestLogDao);
        registerDao(ServiceRequestFile.class, serviceRequestFileDao);
        registerDao(ServiceRequestPhoto.class, serviceRequestPhotoDao);
        registerDao(ServiceRequest.class, serviceRequestDao);
        registerDao(AppointmentAttender.class, appointmentAttenderDao);
        registerDao(Appointment.class, appointmentDao);
        registerDao(PotSell.class, potSellDao);
        registerDao(WorkType.class, workTypeDao);
        registerDao(CleaningReason.class, cleaningReasonDao);
        registerDao(FacilityUrgencyType.class, facilityUrgencyTypeDao);
        registerDao(Fake.class, fakeDao);
        registerDao(OrioType.class, orioTypeDao);
        registerDao(OrioArticle.class, orioArticleDao);
    }

	public void clear() {
		actTypeDaoConfig.clearIdentityScope();
		actReasonDaoConfig.clearIdentityScope();
		contactClientDaoConfig.clearIdentityScope();
		contactAccountDaoConfig.clearIdentityScope();
		clientDaoConfig.clearIdentityScope();
		actAccountDaoConfig.clearIdentityScope();
		actServiceTypeDaoConfig.clearIdentityScope();
		actContactDaoConfig.clearIdentityScope();
		nomenclatureGroupDaoConfig.clearIdentityScope();
		mobileDaoConfig.clearIdentityScope();
		partTimeDaoConfig.clearIdentityScope();
		scheduleDaoConfig.clearIdentityScope();
		vidTaskDaoConfig.clearIdentityScope();
		taskEmployeeDaoConfig.clearIdentityScope();
		countryDaoConfig.clearIdentityScope();
		personDaoConfig.clearIdentityScope();
		personPhotoDaoConfig.clearIdentityScope();
		taskDaoConfig.clearIdentityScope();
		tSTaskDaoConfig.clearIdentityScope();
		checkInLogDaoConfig.clearIdentityScope();
		requestDaoConfig.clearIdentityScope();
		requestPhotoDaoConfig.clearIdentityScope();
		serviceRequestServantDaoConfig.clearIdentityScope();
		serviceRequestLogDaoConfig.clearIdentityScope();
		serviceRequestFileDaoConfig.clearIdentityScope();
		serviceRequestPhotoDaoConfig.clearIdentityScope();
		serviceRequestDaoConfig.clearIdentityScope();
		appointmentAttenderDaoConfig.clearIdentityScope();
		appointmentDaoConfig.clearIdentityScope();
		potSellDaoConfig.clearIdentityScope();
		workTypeDaoConfig.clearIdentityScope();
		cleaningReasonDaoConfig.clearIdentityScope();
		facilityUrgencyTypeDaoConfig.clearIdentityScope();
		fakeDaoConfig.clearIdentityScope();
		orioTypeDaoConfig.clearIdentityScope();
		orioArticleDaoConfig.clearIdentityScope();
	}

    public ActTypeDao getActTypeDao() {
        return actTypeDao;
    }

    public ActReasonDao getActReasonDao() {
        return actReasonDao;
    }

    public ContactClientDao getContactClientDao() {
        return contactClientDao;
    }

    public ContactAccountDao getContactAccountDao() {
        return contactAccountDao;
    }

    public ClientDao getClientDao() {
        return clientDao;
    }

    public ActAccountDao getActAccountDao() {
        return actAccountDao;
    }

    public ActServiceTypeDao getActServiceTypeDao() {
        return actServiceTypeDao;
    }

    public ActContactDao getActContactDao() {
        return actContactDao;
    }

    public NomenclatureGroupDao getNomenclatureGroupDao() {
        return nomenclatureGroupDao;
    }

    public MobileDao getMobileDao() {
        return mobileDao;
    }

    public PartTimeDao getPartTimeDao() {
        return partTimeDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

    public VidTaskDao getVidTaskDao() {
        return vidTaskDao;
    }

    public TaskEmployeeDao getTaskEmployeeDao() {
        return taskEmployeeDao;
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public PersonPhotoDao getPersonPhotoDao() {
        return personPhotoDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public TSTaskDao getTSTaskDao() {
        return tSTaskDao;
    }

    public CheckInLogDao getCheckInLogDao() {
        return checkInLogDao;
    }

    public RequestDao getRequestDao() {
        return requestDao;
    }

    public RequestPhotoDao getRequestPhotoDao() {
        return requestPhotoDao;
    }

    public ServiceRequestServantDao getServiceRequestServantDao() {
        return serviceRequestServantDao;
    }

    public ServiceRequestLogDao getServiceRequestLogDao() {
        return serviceRequestLogDao;
    }

    public ServiceRequestFileDao getServiceRequestFileDao() {
        return serviceRequestFileDao;
    }

    public ServiceRequestPhotoDao getServiceRequestPhotoDao() {
        return serviceRequestPhotoDao;
    }

    public ServiceRequestDao getServiceRequestDao() {
        return serviceRequestDao;
    }

    public AppointmentAttenderDao getAppointmentAttenderDao() {
        return appointmentAttenderDao;
    }

    public AppointmentDao getAppointmentDao() {
        return appointmentDao;
    }

    public PotSellDao getPotSellDao() {
        return potSellDao;
    }

    public WorkTypeDao getWorkTypeDao() {
        return workTypeDao;
    }

    public CleaningReasonDao getCleaningReasonDao() {
        return cleaningReasonDao;
    }

    public FacilityUrgencyTypeDao getFacilityUrgencyTypeDao() {
        return facilityUrgencyTypeDao;
    }

    public FakeDao getFakeDao() {
        return fakeDao;
    }

    public OrioTypeDao getOrioTypeDao() {
        return orioTypeDao;
    }

    public OrioArticleDao getOrioArticleDao() {
        return orioArticleDao;
    }

}
