package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "FACILITY_URGENCY_TYPE".
 */
public class FacilityUrgencyTypeDao extends AbstractDao<FacilityUrgencyType, Long> {

    public static final String TABLENAME = "FACILITY_URGENCY_TYPE";

    public FacilityUrgencyTypeDao(DaoConfig config) {
        super(config);
    }


    public FacilityUrgencyTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"FACILITY_URGENCY_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID\" INTEGER," + // 1: ID
                "\"URGENCY_TYPE\" TEXT);"); // 2: UrgencyType
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FACILITY_URGENCY_TYPE\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, FacilityUrgencyType entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(2, ID);
        }

        String UrgencyType = entity.getUrgencyType();
        if (UrgencyType != null) {
            stmt.bindString(3, UrgencyType);
        }
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, FacilityUrgencyType entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Integer ID = entity.getID();
		if (ID != null) {
			stmt.bindLong(2, ID);
		}

		String UrgencyType = entity.getUrgencyType();
		if (UrgencyType != null) {
			stmt.bindString(3, UrgencyType);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public FacilityUrgencyType readEntity(Cursor cursor, int offset) {
        FacilityUrgencyType entity = new FacilityUrgencyType( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // ID
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // UrgencyType
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, FacilityUrgencyType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setUrgencyType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

	@Override
	protected final Long updateKeyAfterInsert(FacilityUrgencyType entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(FacilityUrgencyType entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(FacilityUrgencyType entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity FacilityUrgencyType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ID = new Property(1, Integer.class, "ID", false, "ID");
        public final static Property UrgencyType = new Property(2, String.class, "UrgencyType", false, "URGENCY_TYPE");
    }
    
}
