package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "FACILITY_URGENCY_TYPE".
 */
@Entity
public class FacilityUrgencyType {

	@Id
	private Long id;
    private Integer ID;
    private String UrgencyType;

	@Generated
	public FacilityUrgencyType() {
    }

    public FacilityUrgencyType(Long id) {
        this.id = id;
    }

	@Generated
	public FacilityUrgencyType(Long id, Integer ID, String UrgencyType) {
        this.id = id;
        this.ID = ID;
        this.UrgencyType = UrgencyType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public String getUrgencyType() {
        return UrgencyType;
    }

    public void setUrgencyType(String UrgencyType) {
        this.UrgencyType = UrgencyType;
    }

}
