package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "FAKE".
 */
@Entity
public class Fake {

	@Id
	private Long id;
    private String Name;
    private String Pattern;

	@Generated
	public Fake() {
    }

    public Fake(Long id) {
        this.id = id;
    }

	@Generated
	public Fake(Long id, String Name, String Pattern) {
        this.id = id;
        this.Name = Name;
        this.Pattern = Pattern;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getPattern() {
        return Pattern;
    }

    public void setPattern(String Pattern) {
        this.Pattern = Pattern;
    }

}
