package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MOBILE".
 */
@Entity
public class Mobile {

	@Id
	private Long id;
    private Integer mobileId;
    private String json;
    private Boolean send;

	@Generated
	public Mobile() {
    }

    public Mobile(Long id) {
        this.id = id;
    }

	@Generated
	public Mobile(Long id, Integer mobileId, String json, Boolean send) {
        this.id = id;
        this.mobileId = mobileId;
        this.json = json;
        this.send = send;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getMobileId() {
        return mobileId;
    }

    public void setMobileId(Integer mobileId) {
        this.mobileId = mobileId;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public Boolean getSend() {
        return send;
    }

    public void setSend(Boolean send) {
        this.send = send;
    }

}
