package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "NOMENCLATURE_GROUP".
 */
@Entity
public class NomenclatureGroup {

	@Id
	private Long id;
    private Integer nomenclatureGroupId;
    private String code;
    private String name;

	@Generated
	public NomenclatureGroup() {
    }

    public NomenclatureGroup(Long id) {
        this.id = id;
    }

	@Generated
	public NomenclatureGroup(Long id, Integer nomenclatureGroupId, String code, String name) {
        this.id = id;
        this.nomenclatureGroupId = nomenclatureGroupId;
        this.code = code;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNomenclatureGroupId() {
        return nomenclatureGroupId;
    }

    public void setNomenclatureGroupId(Integer nomenclatureGroupId) {
        this.nomenclatureGroupId = nomenclatureGroupId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
