package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "PART_TIME".
 */
public class PartTimeDao extends AbstractDao<PartTime, Long> {

    public static final String TABLENAME = "PART_TIME";

    public PartTimeDao(DaoConfig config) {
        super(config);
    }


    public PartTimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"PART_TIME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PART_TIME_ID\" INTEGER," + // 1: partTimeId
                "\"JSON\" TEXT," + // 2: json
                "\"SEND\" INTEGER);"); // 3: send
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PART_TIME\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, PartTime entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer partTimeId = entity.getPartTimeId();
        if (partTimeId != null) {
            stmt.bindLong(2, partTimeId);
        }

        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(3, json);
        }

        Boolean send = entity.getSend();
		if (send != null) {
			stmt.bindLong(4, send ? 1L: 0L);
		}
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, PartTime entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Integer partTimeId = entity.getPartTimeId();
		if (partTimeId != null) {
			stmt.bindLong(2, partTimeId);
		}

		String json = entity.getJson();
		if (json != null) {
			stmt.bindString(3, json);
		}

		Boolean send = entity.getSend();
		if (send != null) {
			stmt.bindLong(4, send ? 1L : 0L);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public PartTime readEntity(Cursor cursor, int offset) {
        PartTime entity = new PartTime( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // partTimeId
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // json
		        cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // send
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, PartTime entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPartTimeId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setJson(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSend(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
    }

	@Override
	protected final Long updateKeyAfterInsert(PartTime entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(PartTime entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(PartTime entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity PartTime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PartTimeId = new Property(1, Integer.class, "partTimeId", false, "PART_TIME_ID");
        public final static Property Json = new Property(2, String.class, "json", false, "JSON");
        public final static Property Send = new Property(3, Boolean.class, "send", false, "SEND");
    }
    
}
