package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PERSON".
 */
@Entity
public class Person {

	@Id
	private Long id;
    private String DocumentType;
    private String PersonLocalUID;
    private String LastName;
    private String FirstName;
    private String FatherName;
    private java.util.Date BirthDate;
    private String CountryUID;
    private Integer NeedPatentOrPermission;
    private String Sex;
    private String PassportNumber;
    private java.util.Date PassportIssue;
    private String PhoneNumber;
    private String PermissionSeria;
    private String PermissionNumber;
    private java.util.Date PermissionExpiry;
    private String PatentNumber;
    private java.util.Date PatentIssue;
    private java.util.Date PatentExpiry;
    private String SubdivisionUID;
    private String RegionUID;
    private String SubdivisionName;
    private String JobTitleUID;
    private String JobTitleName;
    private String BankUID;
    private String BankName;
    private java.util.Date BankDate;
    private java.util.Date BindDate;
    private String PersonUID;
    private String PersonName;
    private Boolean Card;
    private java.util.Date DismissDate;
    private String DismissReasonUID;
    private String DismissReasonName;

	@Generated
	public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

	@Generated
	public Person(Long id, String DocumentType, String PersonLocalUID, String LastName, String FirstName, String FatherName, java.util.Date BirthDate, String CountryUID, Integer NeedPatentOrPermission, String Sex, String PassportNumber, java.util.Date PassportIssue, String PhoneNumber, String PermissionSeria, String PermissionNumber, java.util.Date PermissionExpiry, String PatentNumber, java.util.Date PatentIssue, java.util.Date PatentExpiry, String SubdivisionUID, String RegionUID, String SubdivisionName, String JobTitleUID, String JobTitleName, String BankUID, String BankName, java.util.Date BankDate, java.util.Date BindDate, String PersonUID, String PersonName, Boolean Card, java.util.Date DismissDate, String DismissReasonUID, String DismissReasonName) {
        this.id = id;
        this.DocumentType = DocumentType;
        this.PersonLocalUID = PersonLocalUID;
        this.LastName = LastName;
        this.FirstName = FirstName;
        this.FatherName = FatherName;
        this.BirthDate = BirthDate;
        this.CountryUID = CountryUID;
        this.NeedPatentOrPermission = NeedPatentOrPermission;
        this.Sex = Sex;
        this.PassportNumber = PassportNumber;
        this.PassportIssue = PassportIssue;
        this.PhoneNumber = PhoneNumber;
        this.PermissionSeria = PermissionSeria;
        this.PermissionNumber = PermissionNumber;
        this.PermissionExpiry = PermissionExpiry;
        this.PatentNumber = PatentNumber;
        this.PatentIssue = PatentIssue;
        this.PatentExpiry = PatentExpiry;
        this.SubdivisionUID = SubdivisionUID;
        this.RegionUID = RegionUID;
        this.SubdivisionName = SubdivisionName;
        this.JobTitleUID = JobTitleUID;
        this.JobTitleName = JobTitleName;
        this.BankUID = BankUID;
        this.BankName = BankName;
        this.BankDate = BankDate;
        this.BindDate = BindDate;
        this.PersonUID = PersonUID;
        this.PersonName = PersonName;
        this.Card = Card;
        this.DismissDate = DismissDate;
        this.DismissReasonUID = DismissReasonUID;
        this.DismissReasonName = DismissReasonName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDocumentType() {
        return DocumentType;
    }

    public void setDocumentType(String DocumentType) {
        this.DocumentType = DocumentType;
    }

    public String getPersonLocalUID() {
        return PersonLocalUID;
    }

    public void setPersonLocalUID(String PersonLocalUID) {
        this.PersonLocalUID = PersonLocalUID;
    }

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    public String getFirstName() {
        return FirstName;
    }

    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    public String getFatherName() {
        return FatherName;
    }

    public void setFatherName(String FatherName) {
        this.FatherName = FatherName;
    }

    public java.util.Date getBirthDate() {
        return BirthDate;
    }

    public void setBirthDate(java.util.Date BirthDate) {
        this.BirthDate = BirthDate;
    }

    public String getCountryUID() {
        return CountryUID;
    }

    public void setCountryUID(String CountryUID) {
        this.CountryUID = CountryUID;
    }

    public Integer getNeedPatentOrPermission() {
        return NeedPatentOrPermission;
    }

    public void setNeedPatentOrPermission(Integer NeedPatentOrPermission) {
        this.NeedPatentOrPermission = NeedPatentOrPermission;
    }

    public String getSex() {
        return Sex;
    }

    public void setSex(String Sex) {
        this.Sex = Sex;
    }

    public String getPassportNumber() {
        return PassportNumber;
    }

    public void setPassportNumber(String PassportNumber) {
        this.PassportNumber = PassportNumber;
    }

    public java.util.Date getPassportIssue() {
        return PassportIssue;
    }

    public void setPassportIssue(java.util.Date PassportIssue) {
        this.PassportIssue = PassportIssue;
    }

    public String getPhoneNumber() {
        return PhoneNumber;
    }

    public void setPhoneNumber(String PhoneNumber) {
        this.PhoneNumber = PhoneNumber;
    }

    public String getPermissionSeria() {
        return PermissionSeria;
    }

    public void setPermissionSeria(String PermissionSeria) {
        this.PermissionSeria = PermissionSeria;
    }

    public String getPermissionNumber() {
        return PermissionNumber;
    }

    public void setPermissionNumber(String PermissionNumber) {
        this.PermissionNumber = PermissionNumber;
    }

    public java.util.Date getPermissionExpiry() {
        return PermissionExpiry;
    }

    public void setPermissionExpiry(java.util.Date PermissionExpiry) {
        this.PermissionExpiry = PermissionExpiry;
    }

    public String getPatentNumber() {
        return PatentNumber;
    }

    public void setPatentNumber(String PatentNumber) {
        this.PatentNumber = PatentNumber;
    }

    public java.util.Date getPatentIssue() {
        return PatentIssue;
    }

    public void setPatentIssue(java.util.Date PatentIssue) {
        this.PatentIssue = PatentIssue;
    }

    public java.util.Date getPatentExpiry() {
        return PatentExpiry;
    }

    public void setPatentExpiry(java.util.Date PatentExpiry) {
        this.PatentExpiry = PatentExpiry;
    }

    public String getSubdivisionUID() {
        return SubdivisionUID;
    }

    public void setSubdivisionUID(String SubdivisionUID) {
        this.SubdivisionUID = SubdivisionUID;
    }

    public String getRegionUID() {
        return RegionUID;
    }

    public void setRegionUID(String RegionUID) {
        this.RegionUID = RegionUID;
    }

    public String getSubdivisionName() {
        return SubdivisionName;
    }

    public void setSubdivisionName(String SubdivisionName) {
        this.SubdivisionName = SubdivisionName;
    }

    public String getJobTitleUID() {
        return JobTitleUID;
    }

    public void setJobTitleUID(String JobTitleUID) {
        this.JobTitleUID = JobTitleUID;
    }

    public String getJobTitleName() {
        return JobTitleName;
    }

    public void setJobTitleName(String JobTitleName) {
        this.JobTitleName = JobTitleName;
    }

    public String getBankUID() {
        return BankUID;
    }

    public void setBankUID(String BankUID) {
        this.BankUID = BankUID;
    }

    public String getBankName() {
        return BankName;
    }

    public void setBankName(String BankName) {
        this.BankName = BankName;
    }

    public java.util.Date getBankDate() {
        return BankDate;
    }

    public void setBankDate(java.util.Date BankDate) {
        this.BankDate = BankDate;
    }

    public java.util.Date getBindDate() {
        return BindDate;
    }

    public void setBindDate(java.util.Date BindDate) {
        this.BindDate = BindDate;
    }

    public String getPersonUID() {
        return PersonUID;
    }

    public void setPersonUID(String PersonUID) {
        this.PersonUID = PersonUID;
    }

    public String getPersonName() {
        return PersonName;
    }

    public void setPersonName(String PersonName) {
        this.PersonName = PersonName;
    }

    public Boolean getCard() {
        return Card;
    }

    public void setCard(Boolean Card) {
        this.Card = Card;
    }

    public java.util.Date getDismissDate() {
        return DismissDate;
    }

    public void setDismissDate(java.util.Date DismissDate) {
        this.DismissDate = DismissDate;
    }

    public String getDismissReasonUID() {
        return DismissReasonUID;
    }

    public void setDismissReasonUID(String DismissReasonUID) {
        this.DismissReasonUID = DismissReasonUID;
    }

    public String getDismissReasonName() {
        return DismissReasonName;
    }

    public void setDismissReasonName(String DismissReasonName) {
        this.DismissReasonName = DismissReasonName;
    }

}
