package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PERSON_PHOTO".
 */
@Entity
public class PersonPhoto {

	@Id
	private Long id;
    private Long PersonId;
    private String PersonLocalUID;
    private String ImageLocalUID;
    private Integer PersonPhotoType;
    private String PersonPhotoUri;

	@Generated
	public PersonPhoto() {
    }

    public PersonPhoto(Long id) {
        this.id = id;
    }

	@Generated
	public PersonPhoto(Long id, Long PersonId, String PersonLocalUID, String ImageLocalUID, Integer PersonPhotoType, String PersonPhotoUri) {
        this.id = id;
        this.PersonId = PersonId;
        this.PersonLocalUID = PersonLocalUID;
        this.ImageLocalUID = ImageLocalUID;
        this.PersonPhotoType = PersonPhotoType;
        this.PersonPhotoUri = PersonPhotoUri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPersonId() {
        return PersonId;
    }

    public void setPersonId(Long PersonId) {
        this.PersonId = PersonId;
    }

    public String getPersonLocalUID() {
        return PersonLocalUID;
    }

    public void setPersonLocalUID(String PersonLocalUID) {
        this.PersonLocalUID = PersonLocalUID;
    }

    public String getImageLocalUID() {
        return ImageLocalUID;
    }

    public void setImageLocalUID(String ImageLocalUID) {
        this.ImageLocalUID = ImageLocalUID;
    }

    public Integer getPersonPhotoType() {
        return PersonPhotoType;
    }

    public void setPersonPhotoType(Integer PersonPhotoType) {
        this.PersonPhotoType = PersonPhotoType;
    }

    public String getPersonPhotoUri() {
        return PersonPhotoUri;
    }

    public void setPersonPhotoUri(String PersonPhotoUri) {
        this.PersonPhotoUri = PersonPhotoUri;
    }

}
