package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "POT_SELL".
 */
@Entity
public class PotSell {

	@Id
	private Long id;
    private Integer ClientID;
    private Integer Number;
    private String Name;

	@Generated
	public PotSell() {
    }

    public PotSell(Long id) {
        this.id = id;
    }

	@Generated
	public PotSell(Long id, Integer ClientID, Integer Number, String Name) {
        this.id = id;
        this.ClientID = ClientID;
        this.Number = Number;
        this.Name = Name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getClientID() {
        return ClientID;
    }

    public void setClientID(Integer ClientID) {
        this.ClientID = ClientID;
    }

    public Integer getNumber() {
        return Number;
    }

    public void setNumber(Integer Number) {
        this.Number = Number;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

}
