package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "POT_SELL".
 */
public class PotSellDao extends AbstractDao<PotSell, Long> {

    public static final String TABLENAME = "POT_SELL";

    public PotSellDao(DaoConfig config) {
        super(config);
    }


    public PotSellDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"POT_SELL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CLIENT_ID\" INTEGER," + // 1: ClientID
                "\"NUMBER\" INTEGER," + // 2: Number
                "\"NAME\" TEXT);"); // 3: Name
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POT_SELL\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, PotSell entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer ClientID = entity.getClientID();
        if (ClientID != null) {
            stmt.bindLong(2, ClientID);
        }

        Integer Number = entity.getNumber();
        if (Number != null) {
            stmt.bindLong(3, Number);
        }

        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(4, Name);
        }
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, PotSell entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Integer ClientID = entity.getClientID();
		if (ClientID != null) {
			stmt.bindLong(2, ClientID);
		}

		Integer Number = entity.getNumber();
		if (Number != null) {
			stmt.bindLong(3, Number);
		}

		String Name = entity.getName();
		if (Name != null) {
			stmt.bindString(4, Name);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public PotSell readEntity(Cursor cursor, int offset) {
        PotSell entity = new PotSell( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // ClientID
		        cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // Number
		        cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // Name
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, PotSell entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClientID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setNumber(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
    }

	@Override
	protected final Long updateKeyAfterInsert(PotSell entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(PotSell entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(PotSell entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity PotSell.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClientID = new Property(1, Integer.class, "ClientID", false, "CLIENT_ID");
        public final static Property Number = new Property(2, Integer.class, "Number", false, "NUMBER");
        public final static Property Name = new Property(3, String.class, "Name", false, "NAME");
    }
    
}
