package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "REQUEST".
 */
@Entity
public class Request {

	@Id
	private Long id;
    private Integer InternalServiceRequestID;
    private String ServiceRequestUID;
    private Integer ClientID;
    private Integer DirectumID;
    private String ServiceTypeUID;
    private String WorkTypeUID;
    private String UrgencyTypeName;
    private Integer CleaningReasonID;
    private String Content;
    private java.util.Date DesiredDate;
    private String Comment;
    private String Type;
    private Integer ArrivalTimeRequired;
    private Boolean Changed;

	@Generated
	public Request() {
    }

    public Request(Long id) {
        this.id = id;
    }

	@Generated
	public Request(Long id, Integer InternalServiceRequestID, String ServiceRequestUID, Integer ClientID, Integer DirectumID, String ServiceTypeUID, String WorkTypeUID, String UrgencyTypeName, Integer CleaningReasonID, String Content, java.util.Date DesiredDate, String Comment, String Type, Integer ArrivalTimeRequired, Boolean Changed) {
        this.id = id;
        this.InternalServiceRequestID = InternalServiceRequestID;
        this.ServiceRequestUID = ServiceRequestUID;
        this.ClientID = ClientID;
        this.DirectumID = DirectumID;
        this.ServiceTypeUID = ServiceTypeUID;
        this.WorkTypeUID = WorkTypeUID;
        this.UrgencyTypeName = UrgencyTypeName;
        this.CleaningReasonID = CleaningReasonID;
        this.Content = Content;
        this.DesiredDate = DesiredDate;
        this.Comment = Comment;
        this.Type = Type;
        this.ArrivalTimeRequired = ArrivalTimeRequired;
        this.Changed = Changed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getInternalServiceRequestID() {
        return InternalServiceRequestID;
    }

    public void setInternalServiceRequestID(Integer InternalServiceRequestID) {
        this.InternalServiceRequestID = InternalServiceRequestID;
    }

    public String getServiceRequestUID() {
        return ServiceRequestUID;
    }

    public void setServiceRequestUID(String ServiceRequestUID) {
        this.ServiceRequestUID = ServiceRequestUID;
    }

    public Integer getClientID() {
        return ClientID;
    }

    public void setClientID(Integer ClientID) {
        this.ClientID = ClientID;
    }

    public Integer getDirectumID() {
        return DirectumID;
    }

    public void setDirectumID(Integer DirectumID) {
        this.DirectumID = DirectumID;
    }

    public String getServiceTypeUID() {
        return ServiceTypeUID;
    }

    public void setServiceTypeUID(String ServiceTypeUID) {
        this.ServiceTypeUID = ServiceTypeUID;
    }

    public String getWorkTypeUID() {
        return WorkTypeUID;
    }

    public void setWorkTypeUID(String WorkTypeUID) {
        this.WorkTypeUID = WorkTypeUID;
    }

    public String getUrgencyTypeName() {
        return UrgencyTypeName;
    }

    public void setUrgencyTypeName(String UrgencyTypeName) {
        this.UrgencyTypeName = UrgencyTypeName;
    }

    public Integer getCleaningReasonID() {
        return CleaningReasonID;
    }

    public void setCleaningReasonID(Integer CleaningReasonID) {
        this.CleaningReasonID = CleaningReasonID;
    }

    public String getContent() {
        return Content;
    }

    public void setContent(String Content) {
        this.Content = Content;
    }

    public java.util.Date getDesiredDate() {
        return DesiredDate;
    }

    public void setDesiredDate(java.util.Date DesiredDate) {
        this.DesiredDate = DesiredDate;
    }

    public String getComment() {
        return Comment;
    }

    public void setComment(String Comment) {
        this.Comment = Comment;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

    public Integer getArrivalTimeRequired() {
        return ArrivalTimeRequired;
    }

    public void setArrivalTimeRequired(Integer ArrivalTimeRequired) {
        this.ArrivalTimeRequired = ArrivalTimeRequired;
    }

    public Boolean getChanged() {
        return Changed;
    }

    public void setChanged(Boolean Changed) {
        this.Changed = Changed;
    }

}
