package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "REQUEST_PHOTO".
 */
@Entity
public class RequestPhoto {

	@Id
	private Long id;
    private Long RequestID;
    private String PhotoFileName;

	@Generated
	public RequestPhoto() {
    }

    public RequestPhoto(Long id) {
        this.id = id;
    }

	@Generated
	public RequestPhoto(Long id, Long RequestID, String PhotoFileName) {
        this.id = id;
        this.RequestID = RequestID;
        this.PhotoFileName = PhotoFileName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRequestID() {
        return RequestID;
    }

    public void setRequestID(Long RequestID) {
        this.RequestID = RequestID;
    }

    public String getPhotoFileName() {
        return PhotoFileName;
    }

    public void setPhotoFileName(String PhotoFileName) {
        this.PhotoFileName = PhotoFileName;
    }

}
