package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "REQUEST_PHOTO".
 */
public class RequestPhotoDao extends AbstractDao<RequestPhoto, Long> {

    public static final String TABLENAME = "REQUEST_PHOTO";

    public RequestPhotoDao(DaoConfig config) {
        super(config);
    }


    public RequestPhotoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"REQUEST_PHOTO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REQUEST_ID\" INTEGER," + // 1: RequestID
                "\"PHOTO_FILE_NAME\" TEXT);"); // 2: PhotoFileName
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REQUEST_PHOTO\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, RequestPhoto entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Long RequestID = entity.getRequestID();
        if (RequestID != null) {
            stmt.bindLong(2, RequestID);
        }

        String PhotoFileName = entity.getPhotoFileName();
        if (PhotoFileName != null) {
            stmt.bindString(3, PhotoFileName);
        }
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, RequestPhoto entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Long RequestID = entity.getRequestID();
		if (RequestID != null) {
			stmt.bindLong(2, RequestID);
		}

		String PhotoFileName = entity.getPhotoFileName();
		if (PhotoFileName != null) {
			stmt.bindString(3, PhotoFileName);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public RequestPhoto readEntity(Cursor cursor, int offset) {
        RequestPhoto entity = new RequestPhoto( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // RequestID
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // PhotoFileName
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, RequestPhoto entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRequestID(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setPhotoFileName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

	@Override
	protected final Long updateKeyAfterInsert(RequestPhoto entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(RequestPhoto entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(RequestPhoto entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity RequestPhoto.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RequestID = new Property(1, Long.class, "RequestID", false, "REQUEST_ID");
        public final static Property PhotoFileName = new Property(2, String.class, "PhotoFileName", false, "PHOTO_FILE_NAME");
    }
    
}
