package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SCHEDULE".
 */
@Entity
public class Schedule {

	@Id
	private Long id;
    private String ScheduleID;
    private String ScheduleCode;
    private String Position;
    private Integer Quantity;

	@Generated
	public Schedule() {
    }

    public Schedule(Long id) {
        this.id = id;
    }

	@Generated
	public Schedule(Long id, String ScheduleID, String ScheduleCode, String Position, Integer Quantity) {
        this.id = id;
        this.ScheduleID = ScheduleID;
        this.ScheduleCode = ScheduleCode;
        this.Position = Position;
        this.Quantity = Quantity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getScheduleID() {
        return ScheduleID;
    }

    public void setScheduleID(String ScheduleID) {
        this.ScheduleID = ScheduleID;
    }

    public String getScheduleCode() {
        return ScheduleCode;
    }

    public void setScheduleCode(String ScheduleCode) {
        this.ScheduleCode = ScheduleCode;
    }

    public String getPosition() {
        return Position;
    }

    public void setPosition(String Position) {
        this.Position = Position;
    }

    public Integer getQuantity() {
        return Quantity;
    }

    public void setQuantity(Integer Quantity) {
        this.Quantity = Quantity;
    }

}
