package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SERVICE_REQUEST_FILE".
 */
@Entity
public class ServiceRequestFile {

	@Id
	private Long id;
    private Long ServiceRequestID;
    private Integer ServiceRequestFileID;
    private Integer Type;
    private String Ext;

	@Generated
	public ServiceRequestFile() {
    }

    public ServiceRequestFile(Long id) {
        this.id = id;
    }

	@Generated
	public ServiceRequestFile(Long id, Long ServiceRequestID, Integer ServiceRequestFileID, Integer Type, String Ext) {
        this.id = id;
        this.ServiceRequestID = ServiceRequestID;
        this.ServiceRequestFileID = ServiceRequestFileID;
        this.Type = Type;
        this.Ext = Ext;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServiceRequestID() {
        return ServiceRequestID;
    }

    public void setServiceRequestID(Long ServiceRequestID) {
        this.ServiceRequestID = ServiceRequestID;
    }

    public Integer getServiceRequestFileID() {
        return ServiceRequestFileID;
    }

    public void setServiceRequestFileID(Integer ServiceRequestFileID) {
        this.ServiceRequestFileID = ServiceRequestFileID;
    }

    public Integer getType() {
        return Type;
    }

    public void setType(Integer Type) {
        this.Type = Type;
    }

    public String getExt() {
        return Ext;
    }

    public void setExt(String Ext) {
        this.Ext = Ext;
    }

}
