package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SERVICE_REQUEST_LOG".
 */
@Entity
public class ServiceRequestLog {

	@Id
	private Long id;
    private Long ServiceRequestID;
    private String StatusSetOn;
    private String Status;
    private String StatusSetByFullName;
    private String Comment;

	@Generated
	public ServiceRequestLog() {
    }

    public ServiceRequestLog(Long id) {
        this.id = id;
    }

	@Generated
	public ServiceRequestLog(Long id, Long ServiceRequestID, String StatusSetOn, String Status, String StatusSetByFullName, String Comment) {
        this.id = id;
        this.ServiceRequestID = ServiceRequestID;
        this.StatusSetOn = StatusSetOn;
        this.Status = Status;
        this.StatusSetByFullName = StatusSetByFullName;
        this.Comment = Comment;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServiceRequestID() {
        return ServiceRequestID;
    }

    public void setServiceRequestID(Long ServiceRequestID) {
        this.ServiceRequestID = ServiceRequestID;
    }

    public String getStatusSetOn() {
        return StatusSetOn;
    }

    public void setStatusSetOn(String StatusSetOn) {
        this.StatusSetOn = StatusSetOn;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getStatusSetByFullName() {
        return StatusSetByFullName;
    }

    public void setStatusSetByFullName(String StatusSetByFullName) {
        this.StatusSetByFullName = StatusSetByFullName;
    }

    public String getComment() {
        return Comment;
    }

    public void setComment(String Comment) {
        this.Comment = Comment;
    }

}
