package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SERVICE_REQUEST_PHOTO".
 */
@Entity
public class ServiceRequestPhoto {

	@Id
	private Long id;
    private Long ServiceRequestID;
    private Integer ServiceRequestFileID;
    private String PhotoFileName;

	@Generated
	public ServiceRequestPhoto() {
    }

    public ServiceRequestPhoto(Long id) {
        this.id = id;
    }

	@Generated
	public ServiceRequestPhoto(Long id, Long ServiceRequestID, Integer ServiceRequestFileID, String PhotoFileName) {
        this.id = id;
        this.ServiceRequestID = ServiceRequestID;
        this.ServiceRequestFileID = ServiceRequestFileID;
        this.PhotoFileName = PhotoFileName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getServiceRequestID() {
        return ServiceRequestID;
    }

    public void setServiceRequestID(Long ServiceRequestID) {
        this.ServiceRequestID = ServiceRequestID;
    }

    public Integer getServiceRequestFileID() {
        return ServiceRequestFileID;
    }

    public void setServiceRequestFileID(Integer ServiceRequestFileID) {
        this.ServiceRequestFileID = ServiceRequestFileID;
    }

    public String getPhotoFileName() {
        return PhotoFileName;
    }

    public void setPhotoFileName(String PhotoFileName) {
        this.PhotoFileName = PhotoFileName;
    }

}
