package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TASK".
 */
@Entity
public class Task {

	@Id
	private Long id;
    private String ActUID;
    private Integer ClientID;
    private Integer AccountID;
    private java.util.Date DueDate;
    private String ExecutorLogin;
    private String Result;
    private String Status;
    private String Subject;
    private String Text;
    private Integer TypeID;
    private Integer VidID;
    private String TaskUID;
    private java.util.Date CreatedOn;
    private String ServiceTypeUID;
    private Integer PotSellNumber;
    private Integer ContactID;
    private String ControlComment;
    private Boolean Changed;

	@Generated
	public Task() {
    }

    public Task(Long id) {
        this.id = id;
    }

	@Generated
	public Task(Long id, String ActUID, Integer ClientID, Integer AccountID, java.util.Date DueDate, String ExecutorLogin, String Result, String Status, String Subject, String Text, Integer TypeID, Integer VidID, String TaskUID, java.util.Date CreatedOn, String ServiceTypeUID, Integer PotSellNumber, Integer ContactID, String ControlComment, Boolean Changed) {
        this.id = id;
        this.ActUID = ActUID;
        this.ClientID = ClientID;
        this.AccountID = AccountID;
        this.DueDate = DueDate;
        this.ExecutorLogin = ExecutorLogin;
        this.Result = Result;
        this.Status = Status;
        this.Subject = Subject;
        this.Text = Text;
        this.TypeID = TypeID;
        this.VidID = VidID;
        this.TaskUID = TaskUID;
        this.CreatedOn = CreatedOn;
        this.ServiceTypeUID = ServiceTypeUID;
        this.PotSellNumber = PotSellNumber;
        this.ContactID = ContactID;
        this.ControlComment = ControlComment;
        this.Changed = Changed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getActUID() {
        return ActUID;
    }

    public void setActUID(String ActUID) {
        this.ActUID = ActUID;
    }

    public Integer getClientID() {
        return ClientID;
    }

    public void setClientID(Integer ClientID) {
        this.ClientID = ClientID;
    }

    public Integer getAccountID() {
        return AccountID;
    }

    public void setAccountID(Integer AccountID) {
        this.AccountID = AccountID;
    }

    public java.util.Date getDueDate() {
        return DueDate;
    }

    public void setDueDate(java.util.Date DueDate) {
        this.DueDate = DueDate;
    }

    public String getExecutorLogin() {
        return ExecutorLogin;
    }

    public void setExecutorLogin(String ExecutorLogin) {
        this.ExecutorLogin = ExecutorLogin;
    }

    public String getResult() {
        return Result;
    }

    public void setResult(String Result) {
        this.Result = Result;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getSubject() {
        return Subject;
    }

    public void setSubject(String Subject) {
        this.Subject = Subject;
    }

    public String getText() {
        return Text;
    }

    public void setText(String Text) {
        this.Text = Text;
    }

    public Integer getTypeID() {
        return TypeID;
    }

    public void setTypeID(Integer TypeID) {
        this.TypeID = TypeID;
    }

    public Integer getVidID() {
        return VidID;
    }

    public void setVidID(Integer VidID) {
        this.VidID = VidID;
    }

    public String getTaskUID() {
        return TaskUID;
    }

    public void setTaskUID(String TaskUID) {
        this.TaskUID = TaskUID;
    }

    public java.util.Date getCreatedOn() {
        return CreatedOn;
    }

    public void setCreatedOn(java.util.Date CreatedOn) {
        this.CreatedOn = CreatedOn;
    }

    public String getServiceTypeUID() {
        return ServiceTypeUID;
    }

    public void setServiceTypeUID(String ServiceTypeUID) {
        this.ServiceTypeUID = ServiceTypeUID;
    }

    public Integer getPotSellNumber() {
        return PotSellNumber;
    }

    public void setPotSellNumber(Integer PotSellNumber) {
        this.PotSellNumber = PotSellNumber;
    }

    public Integer getContactID() {
        return ContactID;
    }

    public void setContactID(Integer ContactID) {
        this.ContactID = ContactID;
    }

    public String getControlComment() {
        return ControlComment;
    }

    public void setControlComment(String ControlComment) {
        this.ControlComment = ControlComment;
    }

    public Boolean getChanged() {
        return Changed;
    }

    public void setChanged(Boolean Changed) {
        this.Changed = Changed;
    }

}
