package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "TASK_EMPLOYEE".
 */
public class TaskEmployeeDao extends AbstractDao<TaskEmployee, Long> {

    public static final String TABLENAME = "TASK_EMPLOYEE";

    public TaskEmployeeDao(DaoConfig config) {
        super(config);
    }


    public TaskEmployeeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"TASK_EMPLOYEE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TASK_EMPLOYEE_LOGIN\" TEXT," + // 1: TaskEmployeeLogin
                "\"TASK_EMPLOYEE_NAME\" TEXT);"); // 2: TaskEmployeeName
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_EMPLOYEE\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, TaskEmployee entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String TaskEmployeeLogin = entity.getTaskEmployeeLogin();
        if (TaskEmployeeLogin != null) {
            stmt.bindString(2, TaskEmployeeLogin);
        }

        String TaskEmployeeName = entity.getTaskEmployeeName();
        if (TaskEmployeeName != null) {
            stmt.bindString(3, TaskEmployeeName);
        }
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, TaskEmployee entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		String TaskEmployeeLogin = entity.getTaskEmployeeLogin();
		if (TaskEmployeeLogin != null) {
			stmt.bindString(2, TaskEmployeeLogin);
		}

		String TaskEmployeeName = entity.getTaskEmployeeName();
		if (TaskEmployeeName != null) {
			stmt.bindString(3, TaskEmployeeName);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public TaskEmployee readEntity(Cursor cursor, int offset) {
        TaskEmployee entity = new TaskEmployee( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // TaskEmployeeLogin
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // TaskEmployeeName
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, TaskEmployee entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTaskEmployeeLogin(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTaskEmployeeName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

	@Override
	protected final Long updateKeyAfterInsert(TaskEmployee entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(TaskEmployee entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(TaskEmployee entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity TaskEmployee.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TaskEmployeeLogin = new Property(1, String.class, "TaskEmployeeLogin", false, "TASK_EMPLOYEE_LOGIN");
        public final static Property TaskEmployeeName = new Property(2, String.class, "TaskEmployeeName", false, "TASK_EMPLOYEE_NAME");
    }
    
}
