package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TASK_EMPLOYEE".
 */
@Entity
public class TaskEmployee {

	@Id
	private Long id;
    private String TaskEmployeeLogin;
    private String TaskEmployeeName;

	@Generated
	public TaskEmployee() {
    }

    public TaskEmployee(Long id) {
        this.id = id;
    }

	@Generated
	public TaskEmployee(Long id, String TaskEmployeeLogin, String TaskEmployeeName) {
        this.id = id;
        this.TaskEmployeeLogin = TaskEmployeeLogin;
        this.TaskEmployeeName = TaskEmployeeName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTaskEmployeeLogin() {
        return TaskEmployeeLogin;
    }

    public void setTaskEmployeeLogin(String TaskEmployeeLogin) {
        this.TaskEmployeeLogin = TaskEmployeeLogin;
    }

    public String getTaskEmployeeName() {
        return TaskEmployeeName;
    }

    public void setTaskEmployeeName(String TaskEmployeeName) {
        this.TaskEmployeeName = TaskEmployeeName;
    }

}
