package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TSTASK".
 */
@Entity
public class TSTask {

	@Id
	private Long id;
    private String ID;
    private String Title;
    private String DetailedResult;
    private String DueDate;
    private String ClientName;
    private String AccountName;
    private String AccountAddress;
    private String ContactName;
    private String Executor;
    private String Status;
    private String ControlComment;
    private String Author;

	@Generated
	public TSTask() {
    }

    public TSTask(Long id) {
        this.id = id;
    }

	@Generated
	public TSTask(Long id, String ID, String Title, String DetailedResult, String DueDate, String ClientName, String AccountName, String AccountAddress, String ContactName, String Executor, String Status, String ControlComment, String Author) {
        this.id = id;
        this.ID = ID;
        this.Title = Title;
        this.DetailedResult = DetailedResult;
        this.DueDate = DueDate;
        this.ClientName = ClientName;
        this.AccountName = AccountName;
        this.AccountAddress = AccountAddress;
        this.ContactName = ContactName;
        this.Executor = Executor;
        this.Status = Status;
        this.ControlComment = ControlComment;
        this.Author = Author;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getDetailedResult() {
        return DetailedResult;
    }

    public void setDetailedResult(String DetailedResult) {
        this.DetailedResult = DetailedResult;
    }

    public String getDueDate() {
        return DueDate;
    }

    public void setDueDate(String DueDate) {
        this.DueDate = DueDate;
    }

    public String getClientName() {
        return ClientName;
    }

    public void setClientName(String ClientName) {
        this.ClientName = ClientName;
    }

    public String getAccountName() {
        return AccountName;
    }

    public void setAccountName(String AccountName) {
        this.AccountName = AccountName;
    }

    public String getAccountAddress() {
        return AccountAddress;
    }

    public void setAccountAddress(String AccountAddress) {
        this.AccountAddress = AccountAddress;
    }

    public String getContactName() {
        return ContactName;
    }

    public void setContactName(String ContactName) {
        this.ContactName = ContactName;
    }

    public String getExecutor() {
        return Executor;
    }

    public void setExecutor(String Executor) {
        this.Executor = Executor;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getControlComment() {
        return ControlComment;
    }

    public void setControlComment(String ControlComment) {
        this.ControlComment = ControlComment;
    }

    public String getAuthor() {
        return Author;
    }

    public void setAuthor(String Author) {
        this.Author = Author;
    }

}
