package database;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "VID_TASK".
 */
@Entity
public class VidTask {

	@Id
	private Long id;
    private Integer VidTaskID;
    private String VidTaskName;

	@Generated
	public VidTask() {
    }

    public VidTask(Long id) {
        this.id = id;
    }

	@Generated
	public VidTask(Long id, Integer VidTaskID, String VidTaskName) {
        this.id = id;
        this.VidTaskID = VidTaskID;
        this.VidTaskName = VidTaskName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getVidTaskID() {
        return VidTaskID;
    }

    public void setVidTaskID(Integer VidTaskID) {
        this.VidTaskID = VidTaskID;
    }

    public String getVidTaskName() {
        return VidTaskName;
    }

    public void setVidTaskName(String VidTaskName) {
        this.VidTaskName = VidTaskName;
    }

}
