package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "VID_TASK".
 */
public class VidTaskDao extends AbstractDao<VidTask, Long> {

    public static final String TABLENAME = "VID_TASK";

    public VidTaskDao(DaoConfig config) {
        super(config);
    }


    public VidTaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"VID_TASK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"VID_TASK_ID\" INTEGER," + // 1: VidTaskID
                "\"VID_TASK_NAME\" TEXT);"); // 2: VidTaskName
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VID_TASK\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, VidTask entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer VidTaskID = entity.getVidTaskID();
        if (VidTaskID != null) {
            stmt.bindLong(2, VidTaskID);
        }

        String VidTaskName = entity.getVidTaskName();
        if (VidTaskName != null) {
            stmt.bindString(3, VidTaskName);
        }
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, VidTask entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		Integer VidTaskID = entity.getVidTaskID();
		if (VidTaskID != null) {
			stmt.bindLong(2, VidTaskID);
		}

		String VidTaskName = entity.getVidTaskName();
		if (VidTaskName != null) {
			stmt.bindString(3, VidTaskName);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public VidTask readEntity(Cursor cursor, int offset) {
        VidTask entity = new VidTask( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // VidTaskID
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // VidTaskName
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, VidTask entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVidTaskID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setVidTaskName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

	@Override
	protected final Long updateKeyAfterInsert(VidTask entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(VidTask entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(VidTask entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity VidTask.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VidTaskID = new Property(1, Integer.class, "VidTaskID", false, "VID_TASK_ID");
        public final static Property VidTaskName = new Property(2, String.class, "VidTaskName", false, "VID_TASK_NAME");
    }
    
}
