package database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "WORK_TYPE".
 */
public class WorkTypeDao extends AbstractDao<WorkType, Long> {

    public static final String TABLENAME = "WORK_TYPE";

    public WorkTypeDao(DaoConfig config) {
        super(config);
    }


    public WorkTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(Database db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "\"WORK_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SYSTEM_GUID\" TEXT," + // 1: SystemGUID
                "\"SYSTEM_NAME\" TEXT);"); // 2: SystemName
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(Database db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WORK_TYPE\"";
        db.execSQL(sql);
	}

	@Override
	protected final void bindValues(DatabaseStatement stmt, WorkType entity) {
		stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String SystemGUID = entity.getSystemGUID();
        if (SystemGUID != null) {
            stmt.bindString(2, SystemGUID);
        }

        String SystemName = entity.getSystemName();
        if (SystemName != null) {
            stmt.bindString(3, SystemName);
        }
	}

	@Override
	protected final void bindValues(SQLiteStatement stmt, WorkType entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		String SystemGUID = entity.getSystemGUID();
		if (SystemGUID != null) {
			stmt.bindString(2, SystemGUID);
		}

		String SystemName = entity.getSystemName();
		if (SystemName != null) {
			stmt.bindString(3, SystemName);
		}
	}

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public WorkType readEntity(Cursor cursor, int offset) {
        WorkType entity = new WorkType( //
		        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
		        cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // SystemGUID
		        cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // SystemName
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, WorkType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSystemGUID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSystemName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

	@Override
	protected final Long updateKeyAfterInsert(WorkType entity, long rowId) {
		entity.setId(rowId);
		return rowId;
    }
    
    @Override
    public Long getKey(WorkType entity) {
	    if(entity != null) {
		    return entity.getId();
        } else {
            return null;
	    }
    }

	@Override
	public boolean hasKey(WorkType entity) {
		return entity.getId() != null;
	}

	@Override
	protected final boolean isEntityUpdateable() {
		return true;
    }

    /**
     * Properties of entity WorkType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SystemGUID = new Property(1, String.class, "SystemGUID", false, "SYSTEM_GUID");
        public final static Property SystemName = new Property(2, String.class, "SystemName", false, "SYSTEM_NAME");
    }
    
}
